name: build images

on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push nextwiki next
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          file: nextwiki_next.Dockerfile
          build-args: |
            NEXT_PUBLIC_HOME_URL=https://nextwiki.zizdlp.com/
            NEXT_PUBLIC_USE_HTTPS=true
          push: true
          tags: zizdlp/nextwiki_next:latest