import "./globals.css";

import { i18n } from "../../i18n-config";
import { Locale } from "@/i18n-config";
import SideBarProvider from "@/providers/SideBarProvider";
import ThemeToggleProvider from "@/providers/ThemeToggleProvider";
import RepoSideBar from "@/components/sidebars/RepoSideBar";
import NavBar from "@/components/navbars/NavBar";
import ToastProvider from "@/providers/ToastProvider";
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
export const metadata = {
  title: "nextwiki",
  description: "Generated by @zizdlp",
};
export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <head>
        <link rel="icon" href="/60.png" sizes="any" />
      </head>
      <body className="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 min-h-screen">
        <ThemeToggleProvider>
          <SideBarProvider>
            <NavBar lang={params.lang} />
            <ToastProvider />
            <RepoSideBar />
            {children}
          </SideBarProvider>
        </ThemeToggleProvider>
      </body>
    </html>
  );
}
